# SPDX-FileCopyrightText: 2026 Scenario Inc.
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate the local MCP reference from source AST without importing Blender."""

import argparse
import ast
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
START, END = "<!-- tools:start -->", "<!-- tools:end -->"
GROUPS = (
    ("Scene tools (run on Blender's main thread)", "scenario/mcp/tools_blender.py"),
    ("Scenario tools", "scenario/mcp/tools_scenario.py"),
)


def _value(node):
    try:
        return ast.literal_eval(node)
    except (ValueError, TypeError):
        return ast.unparse(node)


def _properties(node, assignments):
    if not isinstance(node, ast.Dict):
        raise ValueError("Tool properties must be a dictionary")
    result = {}
    for key, value in zip(node.keys, node.values, strict=True):
        if key is None:
            if not isinstance(value, ast.Name) or value.id not in assignments:
                raise ValueError("Only named literal property fragments are supported")
            # Shared fragments themselves must be literal dictionaries; no execution.
            fragment = ast.literal_eval(assignments[value.id])
            if not isinstance(fragment, dict):
                raise ValueError("Tool property fragments must be dictionaries")
            result.update(fragment)
        else:
            if not isinstance(value, ast.Dict):
                raise ValueError("Each tool property must have a dictionary schema")
            result[ast.literal_eval(key)] = {
                ast.literal_eval(k): _value(v)
                for k, v in zip(value.keys, value.values, strict=True)
            }
    return result


def parse_specs(path):
    tree = ast.parse(Path(path).read_text(encoding="utf-8"))
    assignments = {
        node.targets[0].id: node.value
        for node in tree.body
        if isinstance(node, ast.Assign) and isinstance(node.targets[0], ast.Name)
    }
    specs = assignments.get("SPECS")
    if not isinstance(specs, (ast.Tuple, ast.List)):
        raise ValueError("Missing literal SPECS sequence")
    tools = []
    for call in specs.elts:
        if (
            not isinstance(call, ast.Call)
            or not isinstance(call.func, ast.Name)
            or call.func.id != "ToolSpec"
        ):
            raise ValueError("SPECS must contain ToolSpec calls")
        name, description = (ast.literal_eval(arg) for arg in call.args[:2])
        schema = call.args[2]
        if (
            not isinstance(schema, ast.Call)
            or not isinstance(schema.func, ast.Name)
            or schema.func.id != "_schema"
        ):
            raise ValueError("Tool schema must use _schema")
        tools.append(
            {
                "name": name,
                "description": description,
                "properties": _properties(schema.args[0], assignments),
                "required": ast.literal_eval(schema.args[1]) if len(schema.args) > 1 else [],
                "annotations": ast.literal_eval(call.args[4]) if len(call.args) > 4 else {},
            }
        )
    names = [tool["name"] for tool in tools]
    if len(names) != len(set(names)):
        raise ValueError("Duplicate tool names")
    return tools


def _cell(value):
    return str(value).replace("|", "\\|").replace("\n", " ").replace("\r", " ")


def render(groups):
    lines = [
        "Generated by `tools/gen_mcp_docs.py` from `scenario/mcp/tools_*.py`.",
        "Do not edit this block by hand; run `make mcp-docs`. An asterisk marks a required argument.",
    ]
    for title, tools in groups:
        lines.extend(
            [
                "",
                f"### {title}",
                "",
                "| Tool | Description | Arguments | Notes |",
                "| --- | --- | --- | --- |",
            ]
        )
        for tool in tools:
            args = []
            for name, spec in tool["properties"].items():
                required = "*" if name in tool["required"] else ""
                argument = f"`{name}`{required}: {_cell(spec.get('type', 'value'))}"
                if "enum" in spec:
                    argument += f" ({_cell(spec['enum']) if isinstance(spec['enum'], list) else 'enum: see tools/list'})"
                if spec.get("description"):
                    argument += f"; {_cell(spec['description'])}"
                args.append(argument)
            description = tool["description"]
            notes = []
            if tool["annotations"].get("readOnlyHint"):
                notes.append("read-only annotation")
            if tool["annotations"].get("destructiveHint"):
                notes.append("destructive annotation")
            if re.search(r"\bGUI\b", description) or "Do not use in background mode" in description:
                notes.append("GUI required")
            if "spends the user's credits" in description:
                notes.append("spends credits")
            if "Disabled by default" in description:
                notes.append("Python preference gate; off by default")
            lines.append(
                f"| `{tool['name']}` | {_cell(description.splitlines()[0])} | {'<br>'.join(args) or 'none'} | {'; '.join(notes) or '-'} |"
            )
    return "\n".join(lines) + "\n"


def generated(root=ROOT):
    return render([(title, parse_specs(root / path)) for title, path in GROUPS])


def replace_block(document, block):
    if document.count(START) != 1 or document.count(END) != 1:
        raise ValueError("MCP reference needs exactly one generated block")
    if document.index(END) < document.index(START):
        raise ValueError("MCP generated block markers are reversed")
    before, rest = document.split(START)
    _, after = rest.split(END)
    return before + START + "\n" + block + END + after


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    block = generated()
    if not (args.write or args.check):
        print(block, end="")
        return 0
    path = ROOT / "docs/MCP.md"
    document = path.read_text(encoding="utf-8")
    updated = replace_block(document, block)
    if args.check:
        if document != updated:
            print("MCP tool reference is stale; run make mcp-docs")
            return 1
    else:
        path.write_text(updated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
